# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=4)),
                ('cautionnaire', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
                ('province', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'Colombie-Britanique'), ('MB', 'Manitoba'), ('NB', 'Nouveau-Brunswick'), ('NL', 'Terre-Neuve-et-Labrador'), ('NT', 'Territoires du Nord-Ouest'), ('NS', 'Nouvelle-Écosse'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Île-du-Prince-Édouard'), ('QC', 'Québec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], max_length=200)),
                ('pays', models.CharField(max_length=200)),
                ('codepostal', models.CharField(max_length=7)),
                ('numerostel1', models.CharField(max_length=14)),
                ('numerostel2', models.CharField(max_length=14)),
                ('numerostel3', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('datenaissance', models.DateField()),
                ('appartement', models.CharField(choices=[('M', 'Mixte'), ('NM', 'Non-Mixte')], max_length=200)),
                ('domaine', models.CharField(max_length=200)),
                ('sportetude', models.CharField(choices=[(' ', 'Aucun'), ('ba', 'Badminton'), ('bb', 'BasketBall'), ('cl', 'Cheerleading'), ('cc', 'CrossCountry'), ('fb', 'FootBall'), ('ru', 'Rugby'), ('so', 'Soccer'), ('vb', 'VolleyBall')], max_length=20)),
            ],
        ),
    ]
