# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0023_alter_page_revision_on_delete_behaviour'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demande', models.CharField(choices=[('JAN', 'Ma demande est pour la session commençant en janvier prochain'), ('AOU1', "Le Cégep Garneau est mon premier choix de cégep et ma demande de réservation de chambre est conditionnel à mon acceptation au premier tour d'admission pour l'année scolaire qui commence en août prochain."), ('AOU2', "Le Cégep Garneau est mon premier choix de cégep et ma demande de réservation de chambre est pour le deuxième tour d'admission pour l'année scolaire qui commence en août prochain."), ('AOU3', "Le Cégep Garneau est mon premier choix de cégep et ma demande de réservation de chambre est pour le troisième tour d'admission pour l'année scolaire qui commence en août prochain."), ('COM1', "Le Cégep Garneau n'est pas mon premier choix (Inscrire les précisions dans la section commentaires)"), ('COM2', 'Autre (Inscrire les précisions dans la section commentaires)')], max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=4)),
                ('cautionnaire', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
                ('province', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'Colombie-Britanique'), ('MB', 'Manitoba'), ('NB', 'Nouveau-Brunswick'), ('NL', 'Terre-Neuve-et-Labrador'), ('NT', 'Territoires du Nord-Ouest'), ('NS', 'Nouvelle-Écosse'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Île-du-Prince-Édouard'), ('QC', 'Québec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], max_length=200)),
                ('pays', models.CharField(max_length=200)),
                ('codepostal', models.CharField(max_length=7)),
                ('numerostel1', models.CharField(max_length=14)),
                ('numerostel2', models.CharField(max_length=14)),
                ('numerostel3', models.CharField(max_length=14)),
                ('numerostel4', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('datenaissance', models.DateField()),
                ('appartement', models.CharField(choices=[('M', 'Mixte'), ('NM', 'Non-Mixte')], max_length=200)),
                ('domaine', models.CharField(max_length=200)),
                ('sportetude', models.CharField(choices=[(' ', 'Aucun'), ('ba', 'Badminton'), ('bb', 'BasketBall'), ('cl', 'Cheerleading'), ('cc', 'CrossCountry'), ('fb', 'FootBall'), ('ru', 'Rugby'), ('so', 'Soccer'), ('vb', 'VolleyBall')], max_length=20)),
                ('commentaire', models.TextField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationFormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('confirmation_page_title', models.CharField(help_text='Texte pour le titre de la page merci', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
